name = "read-christophpeter-at"
type = "webpack"
routes = ['https://read.christophpeter.at/*']
zone_id = '70d59b088bb39853667c66a4aa31b3cc'
account_id = '81b00e19169f6ab622f40d0f27bb123f'
usage_model = ''
compatibility_flags = []
workers_dev = false
compatibility_date = "2021-12-30"

[[kv_namespaces]]
binding = "CACHE"
preview_id = "c4b764fb55b448b4932c3958a969301d"
id = "67bb455a9b904022ae53cc04a449661f"