name = "read-chrillo-at"
type = "webpack"
routes = ['https://read.chrillo.at/*']
account_id = '81b00e19169f6ab622f40d0f27bb123f'
compatibility_flags = []
workers_dev = false
compatibility_date = "2021-12-30"
main = "index.js"

[[kv_namespaces]]
binding = "CACHE"
preview_id = "c4b764fb55b448b4932c3958a969301d"
id = "67bb455a9b904022ae53cc04a449661f"